import type { ClimbCall } from './types';
import { daysFromNow, plusHours } from './types';

/**
 * 6 seeded belay climb calls. Distinct from Sessions —
 * these are individual "looking for a partner" broadcasts, not group meetups.
 *
 * Weight ranges chosen so `me` (default 63kg from onboarding) has a mix of
 * weight-safe and not-quite-safe matches (rule of thumb: ±30% mass diff).
 */
export const SEED_CLIMB_CALLS: ClimbCall[] = [
  {
    id: 'call_lilly_top_rope',
    user_id: 'usr_lilly',
    looking_for: 'take_turns',
    category: 'top_rope',
    grade: '5.10–5.11a',
    gym_id: 'gym_sbp_poplar',
    starts_at: daysFromNow(0, 18, 0),
    ends_at: daysFromNow(0, 20, 0),
    note: 'Projecting 5.11a — soft catches please',
    is_friend_only: false,
    status: 'live',
    weight_kg: 58,
    capacity: 2,
    participant_ids: ['usr_lilly'],
  },
  {
    id: 'call_marcus_lead',
    user_id: 'usr_marcus',
    looking_for: 'climber',
    category: 'lead',
    grade: '5.10c',
    gym_id: 'gym_stone_gardens_ballard',
    starts_at: new Date(Date.now() + 30 * 60_000).toISOString(),
    ends_at: plusHours(new Date(Date.now() + 30 * 60_000).toISOString(), 2),
    note: 'Down to mock-lead too',
    is_friend_only: false,
    status: 'live',
    weight_kg: 78,
    capacity: 3,
    participant_ids: ['usr_marcus'],
  },
  {
    id: 'call_priya_top_rope',
    user_id: 'usr_priya',
    looking_for: 'belayer',
    category: 'top_rope',
    grade: '5.10a–5.10c',
    gym_id: 'gym_vertical_world',
    starts_at: daysFromNow(0, 17, 0),
    ends_at: daysFromNow(0, 19, 30),
    note: 'Working the red set — thanks in advance!',
    is_friend_only: false,
    status: 'live',
    weight_kg: 55,
    capacity: 2,
    participant_ids: ['usr_priya'],
  },
  {
    id: 'call_kai_lead',
    user_id: 'usr_kai',
    looking_for: 'take_turns',
    category: 'lead',
    grade: '5.11c–5.12a',
    gym_id: 'gym_vertical_world',
    starts_at: daysFromNow(1, 18, 30),
    ends_at: daysFromNow(1, 20, 30),
    note: 'Bring your projecting energy',
    is_friend_only: false,
    status: 'live',
    weight_kg: 72,
    capacity: 4,
    participant_ids: ['usr_kai', 'usr_ash'],
  },
  {
    id: 'call_ash_top_rope',
    user_id: 'usr_ash',
    looking_for: 'climber',
    category: 'top_rope',
    grade: '5.9–5.10b',
    gym_id: 'gym_stone_gardens_bellevue',
    starts_at: daysFromNow(0, 19, 0),
    ends_at: daysFromNow(0, 21, 0),
    note: 'Happy to give catches, teaching a friend too',
    is_friend_only: false,
    status: 'live',
    weight_kg: 62,
    capacity: 3,
    participant_ids: ['usr_ash'],
  },
  {
    id: 'call_sam_top_rope_tomorrow',
    user_id: 'usr_sam',
    looking_for: 'take_turns',
    category: 'top_rope',
    grade: '5.10a–5.10d',
    gym_id: 'gym_movement_bellevue',
    starts_at: daysFromNow(1, 10, 0),
    ends_at: daysFromNow(1, 12, 0),
    note: 'Sunday morning session, chill vibes',
    is_friend_only: false,
    status: 'live',
    weight_kg: 68,
    capacity: 3,
    participant_ids: ['usr_sam'],
  },
];
