import type { EventItem } from './types';
import { daysFromNow, plusHours } from './types';

/**
 * 8 seeded events — climbing-adjacent and not limited to climbing. Includes
 * identity nights (LGBTQ+ / women+ / BIPOC), mountaineering + backcountry
 * clinics, and a comp night. Two events are hosted by community groups
 * (surfaces the "group admin posts event to Find" flow).
 */
export const SEED_EVENTS: EventItem[] = [
  {
    id: 'evt_queer_climb_night',
    title: 'Queer Climb Night',
    tagline: 'Monthly LGBTQ+ social climb + potluck',
    type: 'identity',
    starts_at: daysFromNow(5, 19, 0),
    ends_at: plusHours(daysFromNow(5, 19, 0), 3),
    venue: 'Seattle Bouldering Project — Poplar',
    gym_id: 'gym_sbp_poplar',
    cost_cents: 0,
    capacity: null,
    attendee_ids: ['usr_priya', 'usr_sam', 'usr_ash', 'usr_riley', 'usr_lilly'],
    waitlist_ids: [],
    host_group_id: 'grp_seattle_queer_climbers',
    age_restricted: false,
    description:
      'Show up for community, snacks, and sends. All grades welcome. New folks paired with a climb buddy at the door.',
    gear_note: 'Shoes + chalk. Rentals available at the front desk.',
  },
  {
    id: 'evt_trad_anchors',
    title: 'Intro to Trad Anchors',
    tagline: 'Hands-on clinic — build + rate anchors indoors',
    type: 'education',
    starts_at: daysFromNow(6, 10, 0),
    ends_at: plusHours(daysFromNow(6, 10, 0), 4),
    venue: 'Vertical World Seattle',
    gym_id: 'gym_vertical_world',
    cost_cents: 2500,
    capacity: 8,
    attendee_ids: ['usr_marcus', 'usr_kai', 'usr_ash'],
    waitlist_ids: [],
    host_group_id: 'grp_cascade_alpine_club',
    age_restricted: false,
    description:
      'Half-day clinic on multi-piece trad anchors — SERENE-A, load distribution, extension risk. Instructor: AMGA SPI.',
    gear_note: 'Bring a harness, ATC, 4 locking carabiners, and 2 double-length slings. Rack provided.',
  },
  {
    id: 'evt_womens_send',
    title: 'Women+ Send Sesh',
    tagline: 'Weekly session for women, trans, and non-binary climbers',
    type: 'identity',
    starts_at: daysFromNow(7, 11, 0),
    ends_at: plusHours(daysFromNow(7, 11, 0), 3),
    venue: 'BlocHaus',
    gym_id: 'gym_blochaus',
    cost_cents: 0,
    capacity: 20,
    attendee_ids: ['usr_priya', 'usr_lilly', 'usr_ash', 'usr_riley'],
    waitlist_ids: [],
    host_group_id: 'grp_women_plus_who_send',
    age_restricted: false,
    description:
      'Show up for a supportive session and take turns projecting. Coaches on the floor for anyone who wants feedback.',
  },
  {
    id: 'evt_backcountry_snow',
    title: 'Backcountry Snow Assessment',
    tagline: 'AIARE 1 prep — snowpack fundamentals',
    type: 'backcountry',
    starts_at: daysFromNow(3, 18, 0),
    ends_at: plusHours(daysFromNow(3, 18, 0), 2),
    venue: 'REI Seattle Flagship',
    cost_cents: 1500,
    capacity: 30,
    attendee_ids: ['usr_kai', 'usr_marcus'],
    waitlist_ids: [],
    host_group_id: 'grp_rainier_mountaineers',
    age_restricted: false,
    description:
      "Classroom session covering snowpack layers, weak-layer identification, and terrain choice. Prereq for AIARE 1 field days.",
  },
  {
    id: 'evt_blochaus_comp',
    title: 'BlocHaus Open',
    tagline: 'Redpoint comp — Rec / Advanced / Open divisions',
    type: 'comp',
    starts_at: daysFromNow(6, 18, 0),
    ends_at: plusHours(daysFromNow(6, 18, 0), 4),
    venue: 'BlocHaus',
    gym_id: 'gym_blochaus',
    cost_cents: 1000,
    capacity: 100,
    attendee_ids: ['usr_jordan', 'usr_priya', 'usr_riley', 'usr_sam'],
    waitlist_ids: [],
    age_restricted: false,
    description:
      'Try 40+ fresh boulders across 3 divisions. Prize pool from local sponsors. Music + food truck onsite.',
  },
  {
    id: 'evt_coffee_climbers',
    title: 'Sunday Coffee Climbers',
    tagline: 'Chill Sunday morning session, coffee in hand',
    type: 'social',
    starts_at: daysFromNow(7, 8, 0),
    ends_at: plusHours(daysFromNow(7, 8, 0), 3),
    venue: 'Seattle Bouldering Project — Poplar',
    gym_id: 'gym_sbp_poplar',
    cost_cents: 0,
    capacity: null,
    attendee_ids: ['usr_lilly', 'usr_sam', 'usr_riley'],
    waitlist_ids: [],
    age_restricted: false,
    description:
      'No agenda. Warm up together, drink coffee, climb whatever. Great for meeting new people at your grade.',
  },
  {
    id: 'evt_intro_multi_pitch',
    title: 'Intro to Multi-Pitch',
    tagline: 'Full-day outdoor clinic at Exit 38',
    type: 'mountaineering',
    starts_at: daysFromNow(14, 8, 0),
    ends_at: plusHours(daysFromNow(14, 8, 0), 8),
    venue: 'Exit 38 — Deception Crags',
    cost_cents: 4000,
    capacity: 6,
    attendee_ids: ['usr_marcus', 'usr_kai'],
    waitlist_ids: ['usr_ash'],
    host_group_id: 'grp_cascade_alpine_club',
    age_restricted: true,
    description:
      'Learn the transition-heavy skills that make multi-pitch fast + safe: belay changeovers, rope management, rappelling with a partner.',
    gear_note: 'Full sport rack, 70m rope, 2 lockers, PAS, helmet. Contact host for full list.',
  },
  {
    id: 'evt_bipoc_meetup',
    title: 'BIPOC Climb Meetup',
    tagline: 'Monthly meetup for BIPOC climbers of all grades',
    type: 'identity',
    starts_at: daysFromNow(5, 18, 0),
    ends_at: plusHours(daysFromNow(5, 18, 0), 3),
    venue: 'Vertical World Seattle',
    gym_id: 'gym_vertical_world',
    cost_cents: 0,
    capacity: null,
    attendee_ids: ['usr_priya', 'usr_sam', 'usr_kai'],
    waitlist_ids: [],
    host_group_id: 'grp_bipoc_climbers_pnw',
    age_restricted: false,
    description:
      'Come climb, meet people, and connect. First-timers welcome — we pair new folks with a partner at the door.',
  },
];
