import type { Session } from './types';
import { daysFromNow, plusHours } from './types';

/**
 * 15 seeded sessions:
 *   • 5 that match the brand-board iPhone mock verbatim (indoor)
 *   • 3 additional indoor to exercise the filter row
 *   • 6 outdoor across Index / Gold Bar / Leavenworth / Vantage / Exit 38 / Little Si
 *   • 1 outdoor boulder at Gold Bar
 *
 * `me` is the mocked signed-in user (added to some participant lists so the
 * Profile tab shows both Upcoming and Past sessions on first launch).
 * Dates are computed at load time via daysFromNow() so the seed always feels
 * fresh — no dead "5 days ago" cards after a reload.
 */
export const SEED_SESSIONS: Session[] = [
  // ── 5 mock-exact INDOOR sessions ────────────────────────────────────────
  {
    id: 'ses_mock_top_rope_circuit',
    category: 'top_rope',
    title: 'Top Rope',
    subtitle: 'All levels welcome',
    starts_at: daysFromNow(0, 17, 0),
    ends_at: plusHours(daysFromNow(0, 17, 0), 2),
    gym_id: 'gym_vertical_world',
    host_id: 'usr_lilly',
    participant_ids: ['usr_lilly', 'usr_sam'],
    capacity: 4,
    vibe: 'chill',
    location_type: 'indoor',
    is_verified_only: false,
    requires_attestation: false,
  },
  {
    id: 'ses_mock_lead_vw',
    category: 'lead',
    title: 'Lead Climb',
    subtitle: '5.10a – 5.11c',
    starts_at: daysFromNow(0, 18, 30),
    ends_at: plusHours(daysFromNow(0, 18, 30), 2),
    gym_id: 'gym_vertical_world',
    host_id: 'usr_kai',
    participant_ids: ['usr_kai', 'usr_lilly', 'usr_ash'],
    capacity: 4,
    vibe: 'projecting',
    location_type: 'indoor',
    is_verified_only: true,
    requires_attestation: false,
  },
  {
    id: 'ses_mock_boulder_blochaus',
    category: 'boulder',
    title: 'Boulder Session',
    subtitle: 'V3 – V6',
    starts_at: daysFromNow(1, 12, 0),
    ends_at: plusHours(daysFromNow(1, 12, 0), 2),
    gym_id: 'gym_blochaus',
    host_id: 'usr_priya',
    participant_ids: ['usr_priya', 'usr_jordan', 'usr_riley', 'usr_sam'],
    capacity: 6,
    vibe: 'social',
    location_type: 'indoor',
    is_verified_only: false,
    requires_attestation: false,
  },
  {
    id: 'ses_mock_lead_sg_ballard',
    category: 'lead',
    title: 'Lead Climb',
    subtitle: '5.9 – 5.10d',
    starts_at: daysFromNow(1, 19, 0),
    ends_at: plusHours(daysFromNow(1, 19, 0), 2),
    gym_id: 'gym_stone_gardens_ballard',
    host_id: 'usr_marcus',
    participant_ids: ['usr_marcus', 'usr_ash'],
    capacity: 3,
    vibe: 'training',
    location_type: 'indoor',
    is_verified_only: true,
    requires_attestation: false,
  },
  {
    id: 'ses_mock_top_rope_sun',
    category: 'top_rope',
    title: 'Top Rope',
    subtitle: 'Beginner friendly',
    starts_at: daysFromNow(7, 11, 0),
    ends_at: plusHours(daysFromNow(7, 11, 0), 2),
    gym_id: 'gym_vertical_world',
    host_id: 'usr_lilly',
    participant_ids: ['usr_lilly'],
    capacity: 2,
    vibe: 'chill',
    location_type: 'indoor',
    is_verified_only: false,
    requires_attestation: false,
  },

  // ── 3 extra INDOOR (for filter testing) ─────────────────────────────────
  {
    id: 'ses_boulder_sbp_beginner',
    category: 'boulder',
    title: 'Boulder Session',
    subtitle: 'V0 – V3 · Beginner meetup',
    starts_at: daysFromNow(0, 20, 0),
    ends_at: plusHours(daysFromNow(0, 20, 0), 2),
    gym_id: 'gym_sbp_poplar',
    host_id: 'usr_jordan',
    participant_ids: ['usr_jordan', 'usr_riley'],
    capacity: 5,
    vibe: 'social',
    location_type: 'indoor',
    is_verified_only: false,
    requires_attestation: false,
  },
  {
    id: 'ses_top_rope_movement_verified',
    category: 'top_rope',
    title: 'Top Rope',
    subtitle: 'Verified belayers only · 5.9 – 5.11a',
    starts_at: daysFromNow(6, 10, 0),
    ends_at: plusHours(daysFromNow(6, 10, 0), 3),
    gym_id: 'gym_movement_bellevue',
    host_id: 'usr_sam',
    participant_ids: ['usr_sam', 'usr_ash', 'usr_lilly'],
    capacity: 6,
    vibe: 'chill',
    location_type: 'indoor',
    is_verified_only: true,
    requires_attestation: false,
    note: 'Working through the new red set. Bring your own draws if you have them.',
  },
  {
    id: 'ses_lead_sg_bellevue_projecting',
    category: 'lead',
    title: 'Lead Climb',
    subtitle: '5.11a – 5.12b · Projecting',
    starts_at: daysFromNow(3, 18, 30),
    ends_at: plusHours(daysFromNow(3, 18, 30), 2),
    gym_id: 'gym_stone_gardens_bellevue',
    host_id: 'usr_kai',
    participant_ids: ['usr_kai'],
    capacity: 3,
    vibe: 'projecting',
    location_type: 'indoor',
    is_verified_only: true,
    requires_attestation: false,
  },

  // ── 6 OUTDOOR ──────────────────────────────────────────────────────────
  {
    id: 'ses_outdoor_exit38',
    category: 'outdoor_sport',
    title: 'Sport Climb',
    subtitle: '5.10a – 5.11c',
    starts_at: daysFromNow(6, 9, 0),
    ends_at: plusHours(daysFromNow(6, 9, 0), 6),
    area: 'Exit 38',
    route_id: 'rt_e38_air_guitar',
    host_id: 'usr_ash',
    participant_ids: ['usr_ash', 'usr_marcus', 'usr_lilly'],
    capacity: 4,
    vibe: 'social',
    location_type: 'outdoor',
    is_verified_only: true,
    requires_attestation: false,
  },
  {
    id: 'ses_outdoor_index_trad',
    category: 'trad',
    title: 'Multi-pitch Trad',
    subtitle: '5.6 · Great Northern Slab',
    starts_at: daysFromNow(7, 7, 0),
    ends_at: plusHours(daysFromNow(7, 7, 0), 8),
    area: 'Index',
    route_id: 'rt_index_gns',
    host_id: 'usr_marcus',
    participant_ids: ['usr_marcus'],
    capacity: 3,
    vibe: 'chill',
    location_type: 'outdoor',
    is_verified_only: true,
    requires_attestation: true,
    note: 'Bringing double rack + double ropes. Attestation required.',
  },
  {
    id: 'ses_outdoor_vantage',
    category: 'outdoor_sport',
    title: 'Sport Climb',
    subtitle: '5.9 – 5.10c',
    starts_at: daysFromNow(6, 8, 0),
    ends_at: plusHours(daysFromNow(6, 8, 0), 8),
    area: 'Vantage',
    route_id: 'rt_vantage_party',
    host_id: 'usr_kai',
    participant_ids: ['usr_kai', 'usr_lilly', 'usr_ash', 'usr_sam'],
    capacity: 5,
    vibe: 'social',
    location_type: 'outdoor',
    is_verified_only: true,
    requires_attestation: false,
    note: 'Camping Friday night at the Coulee. DM for carpool.',
  },
  {
    id: 'ses_outdoor_little_si',
    category: 'outdoor_sport',
    title: 'Sport Climb',
    subtitle: '5.10c – 5.11b',
    starts_at: daysFromNow(5, 17, 0),
    ends_at: plusHours(daysFromNow(5, 17, 0), 4),
    area: 'Little Si',
    route_id: 'rt_lsi_prisoners',
    host_id: 'usr_ash',
    participant_ids: ['usr_ash', 'usr_kai'],
    capacity: 3,
    vibe: 'projecting',
    location_type: 'outdoor',
    is_verified_only: true,
    requires_attestation: false,
  },
  {
    id: 'ses_outdoor_leavenworth',
    category: 'outdoor_sport',
    title: 'Sport Climb',
    subtitle: '5.8 – 5.10a · Icicle Canyon',
    starts_at: daysFromNow(13, 9, 0),
    ends_at: plusHours(daysFromNow(13, 9, 0), 8),
    area: 'Leavenworth',
    route_id: 'rt_leav_canary',
    host_id: 'usr_lilly',
    participant_ids: ['usr_lilly', 'usr_priya'],
    capacity: 4,
    vibe: 'chill',
    location_type: 'outdoor',
    is_verified_only: true,
    requires_attestation: false,
  },
  {
    id: 'ses_outdoor_gold_bar_boulder',
    category: 'outdoor_boulder',
    title: 'Outdoor Bouldering',
    subtitle: 'V4 – V7 · Gold Bar Boulders',
    starts_at: daysFromNow(7, 10, 0),
    ends_at: plusHours(daysFromNow(7, 10, 0), 5),
    area: 'Gold Bar',
    route_id: 'rt_gb_boulder_arete',
    host_id: 'usr_priya',
    participant_ids: ['usr_priya', 'usr_riley'],
    capacity: 4,
    vibe: 'projecting',
    location_type: 'outdoor',
    is_verified_only: false,
    requires_attestation: false,
    note: 'Bringing 3 pads. Please bring another if you have one.',
  },

  // ── 1 extra INDOOR auto-belay social ────────────────────────────────────
  {
    id: 'ses_autobelay_vw',
    category: 'top_rope',
    title: 'Auto-Belay Night',
    subtitle: 'No partner needed · All levels',
    starts_at: daysFromNow(4, 19, 0),
    ends_at: plusHours(daysFromNow(4, 19, 0), 2),
    gym_id: 'gym_vertical_world',
    host_id: 'usr_riley',
    participant_ids: ['usr_riley', 'usr_jordan'],
    capacity: 6,
    vibe: 'social',
    location_type: 'indoor',
    is_verified_only: false,
    requires_attestation: false,
  },

  // ── 2 HIKING (find hiking mates) ─────────────────────────────────────────
  {
    id: 'ses_hike_rattlesnake',
    category: 'hiking',
    title: 'Rattlesnake Ledge sunrise',
    subtitle: '4 mi · moderate · 1,160 ft gain',
    starts_at: daysFromNow(6, 6, 0),
    ends_at: plusHours(daysFromNow(6, 6, 0), 4),
    area: 'Rattlesnake Ledge, North Bend',
    host_id: 'usr_ash',
    participant_ids: ['usr_ash', 'usr_lilly'],
    capacity: 6,
    vibe: 'chill',
    location_type: 'outdoor',
    is_verified_only: false,
    requires_attestation: false,
    note: 'Meet at the trailhead lot 5:30am to catch sunrise up top. Coffee after.',
  },
  {
    id: 'ses_hike_mailbox',
    category: 'hiking',
    title: 'Mailbox Peak (old trail)',
    subtitle: '9.4 mi · hard · 4,000 ft gain',
    starts_at: daysFromNow(13, 7, 0),
    ends_at: plusHours(daysFromNow(13, 7, 0), 7),
    area: 'Mailbox Peak, North Bend',
    host_id: 'usr_kai',
    participant_ids: ['usr_kai'],
    capacity: 4,
    vibe: 'training',
    location_type: 'outdoor',
    is_verified_only: false,
    requires_attestation: false,
    note: 'Steep grind — bring 3L water + layers, weather can turn at the summit.',
  },
];
